server:
  port: 8080
spring:
  application:
    name: cerberus
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    
com:
  behl:
    cerberus:
      unsecured:
        api-path:
          swagger-v3: true
          post:
            - /users
            - /auth/login
          put: 
            - /auth/refresh
      token:
        access-token:
          secret-key: ${JWT_SECRET_KEY}
          validity: 30
        refresh-token:
          validity: 120
      open-api:
        api-version: 1.0.0
        title: Cerberus
        description: Java Backend application using Spring-security to implement JWT based Authentication and Authorization